on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9

    - run: pnpm install

    - run: pnpm package

    - name: Publish
      run: pnpm deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}